# Generated by Django 5.2.12 on 2026-03-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('obs', models.TextField(blank=True, null=True)),
                ('comar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.comar')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.pais')),
                ('tipo_elo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipoelo')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.pais')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoCidade',
            fields=[
                ('sigla', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.estado')),
            ],
        ),
        migrations.AddField(
            model_name='comar',
            name='regiao_cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.regiaocidade'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('versao_so', models.CharField(max_length=50)),
                ('obs', models.TextField(blank=True, null=True)),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='indicadores.om')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.status')),
                ('tipo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipoacesso')),
            ],
        ),
        migrations.CreateModel(
            name='DataVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='DataCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.servidor')),
            ],
        ),
    ]
