# Generated by Django 5.2.12 on 2026-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servidor",
            name="suporte_so",
            field=models.CharField(
                choices=[
                    ("atual", "Atual"),
                    ("suportado", "Suportado"),
                    ("descontinuado", "Descontinuado"),
                ],
                default="atual",
                max_length=20,
            ),
        ),
    ]
