# Generated by Django 6.0.3 on 2026-03-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicadores", "0003_datastatus_delete_datacompra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="om",
            options={"verbose_name": "OM", "verbose_name_plural": "OMs"},
        ),
        migrations.RemoveField(
            model_name="servidor",
            name="om",
        ),
        migrations.AddField(
            model_name="om",
            name="servidor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oms",
                to="indicadores.servidor",
                verbose_name="Servidor",
            ),
        ),
    ]
