from .views_home import *
from .views_indicadores import *
from .views_status import *
from .views_tipo_acesso import *
from .views_tipo_elo import *
from .views_pais import *
from .views_estado import *
from .views_regiao import *
from .views_comar import *
from .views_om import *
from .views_servidor import *
from .views_data_compra import *
from .views_data_visita import *
from .views_usuario import *
